name: Build and Release Nekoray

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Nekoray
      run: |
        bash nekoray_macos_builder.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nekoray_build
        path: |
          nekoray/build/nekoray_amd64.zip
          nekoray/build/nekoray_arm64.zip

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: latest
        release_name: Release ${{ github.sha }}
        body: Automated release of Nekoray ${{ github.sha }}
        draft: false
        prerelease: false
        permissions: write-all

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: |
          nekoray/build/nekoray_amd64.zip
          nekoray/build/nekoray_arm64.zip
        asset_name: nekoray_latest.zip
        asset_content_type: application/zip
