name: Build and Release Nekoray

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    env:
      MACOSX_DEPLOYMENT_TARGET: 10.15

    steps:
      - uses: actions/checkout@v2

      - name: Build Nekoray
        run: |
          bash nekoray_macos_builder.sh
      - name: Upload Artifact for amd64
        uses: actions/upload-artifact@v2
        with:
          name: nekoray_amd64
          path: nekoray/build/nekoray_amd64.zip

      - name: Upload Artifact for arm64
        uses: actions/upload-artifact@v2
        with:
          name: nekoray_arm64
          path: nekoray/build/nekoray_arm64.zip

  create_release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      packages: write
      actions: read
      pull-requests: write
      issues: write


    steps:
      - name: Check latest tag
        id: check_tag
        run: |
          latest_tag=$(git ls-remote --tags --sort=-v:refname https://github.com/MatsuriDayo/nekoray.git | head -n1 | awk '{print $2}' | sed 's/refs\/tags\///')
          echo "Latest tag is ${latest_tag}"
          echo "latest_tag=${latest_tag}" >> $GITHUB_ENV
      - name: Create Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.latest_tag }}
          name: Release ${{ env.latest_tag }}
          body: Automated release of Nekoray ${{ env.latest_tag }}
          draft: false
          prerelease: ${{ contains(env.latest_tag, 'pre') }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nekoray/build/nekoray_amd64.zip
            nekoray/build/nekoray_arm64.zip
          name: Release ${{ env.latest_tag }}
          body: Automated release of Nekoray ${{ env.latest_tag }}
          prerelease: ${{ contains(env.latest_tag, 'pre') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
